# Venzee Gemfile
source 'http://rubygems.org'

gem 'cucumber', '1.3.17'
gem 'selenium-webdriver'
gem 'rspec-expectations'
gem 'ruby-gmail'
gem 'relish'
gem 'rails'
gem 'clipboard'
gem 'json'
gem 'win32screenshot'