# Venzee Gemfile
source 'http://rubygems.org'

gem 'cryptenv'
gem 'json'
gem 'net-ssh', '2.9.2'  # later than 2.9.2 can only work with ruby version 2.x  
gem 'cucumber', '1.3.17'
gem 'selenium-webdriver'
gem 'rspec-expectations'
gem 'ruby-gmail'
gem 'relish'
gem 'rails'
gem 'clipboard'
gem 'win32screenshot'
gem 'google_drive'