# A sample Gemfile
source "https://rubygems.org"


gem 'concurrent-ruby',    '1.0.1'
gem 'cookiejar',          '0.3.0'
gem 'eventmachine',       '1.0.9.1'
gem 'em-socksify',        '0.3.1'
gem 'http_parser.rb',     '0.6.0'
gem 'em-http-request',    '1.1.3'
gem 'faraday-http-cache', '0.4.2'
gem 'hashdiff',           '0.3.0'
gem 'ld-em-eventsource',  '0.2.4'
gem 'net-http-persistent','2.9.4'
gem 'ldclient-rb',        '0.7.0'
